; PBXLoRa v2 - Custom ESP32-WROOM-32E with SX1262 LoRa module
[env:pbxlora-v2]
extends = esp32_base
board = esp32doit-devkit-v1
; upload_port = COM29  ; Change this to your device's COM port (e.g., COM3, COM4, etc.)
; monitor_port = COM11  ; Same port for serial monitoring
build_flags =
  ${esp32_base.build_flags}
  -D PRIVATE_HW
  -D USE_SX1262
  -I variants/esp32/diy/pbxlora_v2